# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\study\NIS3366\Smart-Memo-Manager\mainWindow\ui\resource\mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(900, 700)
        self.frame = CardWidget(mainwindow)
        self.frame.setGeometry(QtCore.QRect(10, 70, 831, 571))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.scrollArea = SmoothScrollArea(self.frame)
        self.scrollArea.setGeometry(QtCore.QRect(9, 6, 811, 551))
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 809, 549))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.frame_2 = CardWidget(mainwindow)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 681, 51))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit = SearchLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 421, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = ComboBox(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(460, 10, 211, 31))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.toolButton = ToolButton(mainwindow)
        self.toolButton.setGeometry(QtCore.QRect(720, 10, 51, 51))
        self.toolButton.setText("")
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = ToolButton(mainwindow)
        self.toolButton_2.setGeometry(QtCore.QRect(790, 10, 51, 51))
        self.toolButton_2.setText("")
        self.toolButton_2.setObjectName("toolButton_2")

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "Form"))
from qfluentwidgets import CardWidget, ComboBox, SearchLineEdit, SmoothScrollArea, ToolButton
