# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\HP\Desktop\Smart-Memo-Manager\mainWindow\ui\resource\memo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_memo(object):
    def setupUi(self, memo):
        memo.setObjectName("memo")
        memo.resize(900, 700)
        self.frame = CardWidget(memo)
        self.frame.setGeometry(QtCore.QRect(20, 80, 811, 551))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textEdit = TextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(30, 40, 751, 491))
        self.textEdit.setObjectName("textEdit")
        self.label = StrongBodyLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(740, 10, 72, 15))
        self.label.setObjectName("label")
        self.frame_3 = CardWidget(memo)
        self.frame_3.setGeometry(QtCore.QRect(20, 10, 471, 51))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.lineEdit_2 = EditableComboBox(self.frame_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 10, 141, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = LineEdit(self.frame_3)
        self.lineEdit.setGeometry(QtCore.QRect(20, 10, 261, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.frame_4 = CardWidget(memo)
        self.frame_4.setGeometry(QtCore.QRect(549, 9, 281, 51))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_2 = CommandBar(self.frame_4)
        self.frame_2.setGeometry(QtCore.QRect(20, 10, 241, 31))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")

        self.retranslateUi(memo)
        QtCore.QMetaObject.connectSlotsByName(memo)

    def retranslateUi(self, memo):
        _translate = QtCore.QCoreApplication.translate
        memo.setWindowTitle(_translate("memo", "Form"))
        self.label.setText(_translate("memo", "共xx字"))
from qfluentwidgets import CardWidget, CommandBar, EditableComboBox, LineEdit, StrongBodyLabel, TextEdit
