# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\HP\Desktop\Smart-Memo-Manager\mainWindow\ui\resource\memo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_memo(object):
    def setupUi(self, memo):
        memo.setObjectName("memo")
        memo.resize(900, 700)
        self.frame = CardWidget(memo)
        self.frame.setGeometry(QtCore.QRect(20, 110, 811, 551))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textEdit = TextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(30, 20, 741, 511))
        self.textEdit.setObjectName("textEdit")
        self.lineEdit = LineEdit(memo)
        self.lineEdit.setGeometry(QtCore.QRect(80, 50, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = EditableComboBox(memo)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 50, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.frame_2 = CommandBar(memo)
        self.frame_2.setGeometry(QtCore.QRect(500, 20, 301, 61))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")

        self.retranslateUi(memo)
        QtCore.QMetaObject.connectSlotsByName(memo)

    def retranslateUi(self, memo):
        _translate = QtCore.QCoreApplication.translate
        memo.setWindowTitle(_translate("memo", "Form"))
from qfluentwidgets import CardWidget, CommandBar, EditableComboBox, LineEdit, TextEdit
