
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\HP\Desktop\Smart-Memo-Manager\mainWindow\ui\resource\mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(900, 700)

        # 创建主布局（垂直布局）
        main_layout = QtWidgets.QVBoxLayout(mainwindow)

        # 顶部搜索和按钮区域
        top_layout = QtWidgets.QHBoxLayout()
        self.frame_2 = CardWidget(mainwindow)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        frame2_layout = QtWidgets.QHBoxLayout(self.frame_2)  # frame_2 内部的布局
        self.lineEdit = SearchLineEdit(self.frame_2)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = ComboBox(self.frame_2)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        frame2_layout.addWidget(self.lineEdit)
        frame2_layout.addWidget(self.pushButton)
        self.toolButton = ToolButton(mainwindow)
        self.toolButton.setText("")
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = ToolButton(mainwindow)
        self.toolButton_2.setText("")
        self.toolButton_2.setObjectName("toolButton_2")

        top_layout.addWidget(self.frame_2)
        top_layout.addWidget(self.toolButton)
        top_layout.addWidget(self.toolButton_2)
        main_layout.addLayout(top_layout)

        # 中间滚动区域
        self.frame = CardWidget(mainwindow)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        frame_layout = QtWidgets.QVBoxLayout(self.frame)  # frame 内部的布局
        self.scrollArea = SmoothScrollArea(self.frame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        frame_layout.addWidget(self.scrollArea)
        main_layout.addWidget(self.frame)  # 将 frame 添加到主布局

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "Form"))


from qfluentwidgets import (
    CardWidget,
    ComboBox,
    SearchLineEdit,
    SmoothScrollArea,
    ToolButton,
)
